TC_03.06.011 |Create Multiconfiguration project
RedRoverSchool/JenkinsQA_JS_07 pull request #144
Opened 2023-11-04 19:40 UTC by MargaritaArcady

https://trello.com/c/d04ukgec/226-tc0306011-create-multiconfiguration-project

2023-11-04 21:26 UTC, SergeiKuznetsov commented
Дубль #62 
https://github.com/RedRoverSchool/JenkinsQA_JS_07/pull/62

2023-11-04 21:33 UTC, SergeiKuznetsov requested changes
Много опечаток в вашем варианте.

2023-11-04 21:33 UTC, SergeiKuznetsov commented on cypress/e2e/multiconfigProject.cy.js
> +        cy.get('a[href="newJob]').click()
```suggestion
        cy.get('a[href="newJob"]').click()
```

2023-11-04 21:33 UTC, SergeiKuznetsov commented on cypress/e2e/multiconfigProject.cy.js
> +        cy.get('td a[href*="job"].jenkins-table_link').should('have.text', 'Projtct1')
```suggestion
        cy.get('td a[href*="job"].jenkins-table__link').should('have.text', 'Project1')
```

2023-11-04 21:33 UTC, SergeiKuznetsov commented on cypress/e2e/multiconfigProject.cy.js
> +})
```suggestion
})

```

2023-11-05 00:41 UTC, qa-tester22 approved these changes

2023-11-05 00:50 UTC, SergeiKuznetsov commented
Вы решили таки попробовать разрешить конфликт через веб-интерфейс гитхаба? Я же просил вас не делать так. 

И в чем смысл конечной правки?

2023-11-05 01:36 UTC, qa-tester22 commented
LGTM!

2023-11-05 01:40 UTC, MargaritaArcady commented
> LGTM!



> LGTM!

Thank you

2023-11-05 01:41 UTC, MargaritaArcady commented
> Вы решили таки попробовать разрешить конфликт через веб-интерфейс гитхаба? Я же просил вас не делать так.
> 
> И в чем смысл конечной правки?

Исправила в своем VSC, и убрала тестовые данные

2023-11-06 08:32 UTC, AlYeMax approved these changes

2023-11-07 19:30 UTC, DavidAffman approved these changes

2023-11-07 20:28 UTC, Sensation3000 approved these changes

2023-11-08 02:00 UTC, SergeiKuznetsov commented on cypress/e2e/multiconfigProject.cy.js
> +    })
```suggestion
    })
```

2023-11-08 02:01 UTC, SergeiKuznetsov commented on cypress/fixtures/multiconfigProject.json
> +}
```suggestion
}
```

2023-11-08 02:03 UTC, SergeiKuznetsov approved these changes

2023-11-08 02:06 UTC, SergeiKuznetsov commented
Когда создаёте коммит непосредственно на гитхабе, то не забывайте его к себе на комп потом скачать через `git pull`.
А то вы потом создали локально ещё коммит от старого состояния и затем героически склеивали раздвоившуюся ветку.

2023-11-09 12:01 UTC, merged