TC_02.04.023 | Dashboard > Command panel on the left side
RedRoverSchool/JenkinsQA_JS_07 pull request #158
Opened 2023-11-05 22:05 UTC by Kamal-Zh

https://trello.com/c/GwDMWKg0/232-tc0204023-dashboard-command-panel-on-the-left-side

2023-11-06 03:55 UTC, Rom-T commented
A very difficult test to read.  Try using a for loop to go through all the elements.

2023-11-07 01:29 UTC, KravchukKseniya requested changes

2023-11-07 01:29 UTC, KravchukKseniya commented on cypress/e2e/Project/dashboardSideMenu.cy.js
> +    //New Item
Avoid comments in your code

2023-11-07 01:29 UTC, KravchukKseniya commented on cypress/e2e/Project/dashboardSideMenu.cy.js
> +    cy.url().should('be.equal', 'http://localhost:8080/view/all/newJob');
Please, do not use this hard code links, check only end points `view/all/newJob`. We discussed that on the last lesson with Maria.
You can use `.should('contain', '/view/all/newJob')` for this purpose.

2023-11-07 01:29 UTC, KravchukKseniya commented on cypress/e2e/Project/dashboardSideMenu.cy.js
> +    });
You need to divide your test case to several test cases. There are a lot of assertions in one test.

At first check that left-side menu have correct text. This code form our first review with Stan can be helpful
https://redroverschool.slack.com/archives/C01DNKMFN73/p1697513993568089?thread_ts=1697513945.186669&cid=C01DNKMFN73

Than check work of every link in separate test.

Also, you can move all data like menu item names and endpoints to fixture file.

2023-11-07 02:09 UTC, Rom-T commented on cypress/e2e/Project/dashboardSideMenu.cy.js
> +    //New Item
Don't neglect Request Changes due to minor errors.

2023-12-14 12:40 UTC, Paul-Korz commented
Hi. Please close your PR and delete branch.

2023-12-16 06:57 UTC, closed without merging