TC_01.01.006 | Sign in to Jerkins > Sign in with invalid password
RedRoverSchool/JenkinsQA_JS_07 pull request #223
Opened 2023-11-12 12:26 UTC by KateKazakovaJS

https://trello.com/c/yUHWu6dv/327-tc0101006-sign-in-to-jerkins-sign-in-with-invalid-password

2023-11-12 12:33 UTC, npkazakova approved these changes

2023-11-12 19:56 UTC, RuslanG13 requested changes

2023-11-12 19:56 UTC, RuslanG13 commented on package-lock.json
>      }
Changes in configuration files are not allowed
`!!Do not push changed files as:

package.json package.lock.json cypress.config.js e2e.js ci.yml cancel.yml globalHooks.js cleanData.js`

2023-11-12 19:59 UTC, RuslanG13 requested changes
Changes in configuration files are not allowed
`!!Do not push changed files as:

package.json package.lock.json cypress.config.js e2e.js ci.yml cancel.yml globalHooks.js cleanData.js`

2023-11-12 20:00 UTC, RuslanG13 requested changes

2023-11-12 20:00 UTC, RuslanG13 commented on package-lock.json
> +      "integrity": "sha512-k0N7BqGhJoJzdh6MuQg1V1ragJiXTh8VUBAZTWjJ9cUq23SG0F0xavOwZbhiP4J3y20xd6jxKx+xNUhkMAi76Q=="
Changes in configuration files are not allowed
`!!Do not push changed files as:

package.json package.lock.json cypress.config.js e2e.js ci.yml cancel.yml globalHooks.js cleanData.js`

2023-11-13 05:12 UTC, Rom-T requested changes
You cannot make changes to the project config files. Please correct

2023-11-14 03:58 UTC, Rom-T approved these changes

2023-11-16 15:42 UTC, RuslanG13 approved these changes

2023-11-16 15:57 UTC, merged