TC_02.03.001 | Dashboard > Check welcomed message
RedRoverSchool/JenkinsQA_JS_07 pull request #7
Opened 2023-10-27 22:19 UTC by KravchukKseniya

https://trello.com/c/JDf807zT/46-tc0203001-dashboard-check-welcomed-message

2023-10-27 23:16 UTC, verafes commented
It's expected to include a pull request (PR) link in the Trello card.

2023-10-27 23:27 UTC, EkBlinova requested changes
Please rename cypress file from dashboardWelcomedMessage.cy.js to dashboard.cy.js since all the tests related to the dashboard will be written in this file

2023-10-27 23:43 UTC, verafes approved these changes

2023-10-28 00:27 UTC, EkBlinova approved these changes

2023-10-28 04:07 UTC, Rom-T approved these changes

2023-10-29 01:16 UTC, merged